version: '3'
services:
  llm:
    build:
      context: ./apps/llm
    container_name: llm
    ports:
      - "5001:5000"
    networks:
      - app-network
    tty: True

networks:
  app-network:
    driver: bridge
